import re

RU_TO_ENG = {
    "ABS": "ABS", "ACOS": "ACOS", "ACOSH": "ACOSH", "ACOT": "ACOT", "ACOTH": "ACOTH",
    "АДРЕС": "ADDRESS", "АМОРУМ": "AMORDEGRC", "АМОРВ": "AMORLINC", "И": "AND",
    "АРАБСКОЕ": "ARABIC", "МАССИВ.В.ТЕКСТ": "ARRAYTOTEXT", "ОБЛАСТИ": "AREAS",
    "ASIN": "ASIN", "ASINH": "ASINH", "ATAN": "ATAN", "ATAN2": "ATAN2", "ATANH": "ATANH",
    "СРОТКЛ": "AVEDEV", "СРЗНАЧ": "AVERAGE", "СРЗНАЧ.ВЗВЕШ": "AVERAGE_WEIGHTED",
    "СРЗНАЧА": "AVERAGEA", "СРЗНАЧЕСЛИ": "AVERAGEIF", "СРЗНАЧЕСЛИМН": "AVERAGEIFS",
    "БАТТЕКСТ": "BAHTTEXT", "ОСНОВАНИЕ": "BASE", "БЕССЕЛЬ.I": "BESSELI",
    "БЕССЕЛЬ.J": "BESSELJ", "БЕССЕЛЬ.K": "BESSELK", "БЕССЕЛЬ.Y": "BESSELY",
    "БЕТА.РАСП": "BETA_DIST", "БЕТА.ОБР": "BETA_INV", "БЕТАРАСП": "BETADIST",
    "БЕТАОБР": "BETAINV", "ДВ.В.ДЕС": "BIN2DEC", "ДВ.В.ШЕСТН": "BIN2HEX",
    "ДВ.В.ВОСЬМ": "BIN2OCT", "БИНОМ.РАСП": "BINOM_DIST",
    "БИНОМ.РАСП.ДИАП": "BINOM_DIST_RANGE", "БИНОМ.ОБР": "BINOM_INV",
    "БИНОМРАСП": "BINOMDIST", "БИТ.И": "BITAND", "БИТ.СДВИГЛ": "BITLSHIFT",
    "БИТ.ИЛИ": "BITOR", "БИТ.СДВИГП": "BITRSHIFT", "БИТ.ИСКЛИЛИ": "BITXOR",
    "ПО.СТОЛБЦАМ": "BYCOL", "ПО.СТРОКАМ": "BYROW", "ОКРВВЕРХ": "CEILING",
    "ОКРВВЕРХ.МАТ": "CEILING_MATH", "ОКРВВЕРХ.ТОЧН": "CEILING_PRECISE",
    "ЯЧЕЙКА": "CELL", "СИМВОЛ": "CHAR", "ХИ2РАСП": "CHIDIST", "ХИ2ОБР": "CHIINV",
    "ХИ2.РАСП": "CHISQ_DIST", "ХИ2.РАСП.ПХ": "CHISQ_DIST_RT", "ХИ2.ОБР": "CHISQ_INV",
    "ХИ2.ОБР.ПХ": "CHISQ_INV_RT", "ХИ2.ТЕСТ": "CHISQ_TEST", "ХИ2ТЕСТ": "CHITEST",
    "ВЫБОР": "CHOOSE", "ВЫБРАТЬ.СТОЛБЦЫ": "CHOOSECOLS", "ВЫБРАТЬ.СТРОКИ": "CHOOSEROWS",
    "ПЕЧСИМВ": "CLEAN", "КОДСИМВ": "CODE", "СТОЛБЕЦ": "COLUMN", "ЧИСЛСТОЛБЦОВ": "COLUMNS",
    "ЧИСЛКОМБ": "COMBIN", "ЧИСЛКОМБА": "COMBINA", "КОМПЛЕКСН": "COMPLEX", "СЦЕП": "CONCAT",
    "СЦЕПИТЬ": "CONCATENATE", "ДОВЕРИТ": "CONFIDENCE", "ДОВЕРИТ.НОРМ": "CONFIDENCE_NORM",
    "ДОВЕРИТ.СТЬЮДЕНТ": "CONFIDENCE_T", "ПРЕОБР": "CONVERT", "КОРРЕЛ": "CORREL",
    "COS": "COS", "COSH": "COSH", "COT": "COT", "COTH": "COTH", "СЧЁТ": "COUNT",
    "СЧЁТЗ": "COUNTA", "СЧИТАТЬПУСТОТЫ": "COUNTBLANK", "СЧЁТЕСЛИ": "COUNTIF",
    "СЧЁТЕСЛИМН": "COUNTIFS", "ДНЕЙКУПОН.ДО": "COUPDAYBS", "ДНЕЙКУПОН": "COUPDAYS",
    "ДНЕЙКУПОН.ПОСЛЕ": "COUPDAYSNC", "ДАТАКУПОН.ПОСЛЕ": "COUPNCD", "ЧИСЛКУПОН": "COUPNUM",
    "ДАТАКУПОН.ДО": "COUPPCD", "КОВАР": "COVAR", "КОВАРИАЦИЯ.П": "COVARIANCE_P",
    "КОВАРИАЦИЯ.В": "COVARIANCE_S", "КРИТБИНОМ": "CRITBINOM", "CSC": "CSC", "CSCH": "CSCH",
    "ОБЩПЛАТ": "CUMIPMT", "ОБЩДОХОД": "CUMPRINC", "ДАТА": "DATE", "РАЗНДАТ": "DATEDIF",
    "ДАТАЗНАЧ": "DATEVALUE", "БСРЗНАЧ": "DAVERAGE", "ДЕНЬ": "DAY", "ДНЕЙ": "DAYS",
    "ДНЕЙ360": "DAYS360", "ФУО": "DB", "БСЧЁТ": "DCOUNT", "БСЧЁТЗ": "DCOUNTA",
    "ДДОБ": "DDB", "ДЕС.В.ДВ": "DEC2BIN", "ДЕС.В.ШЕСТН": "DEC2HEX", "ДЕС.В.ВОСЬМ": "DEC2OCT",
    "ДЕС": "DECIMAL", "ГРАДУСЫ": "DEGREES", "ДЕЛЬТА": "DELTA", "КВАДРОТКЛ": "DEVSQ",
    "БИЗВЛЕЧЬ": "DGET", "СКИДКА": "DISC", "БМАКС": "DMAX", "БМИН": "DMIN",
    "РУБЛЬ": "DOLLAR", "РУБЛЬ.ДЕС": "DOLLARDE", "РУБЛЬ.ДРОБЬ": "DOLLARFR",
    "БПРОИЗВЕД": "DPRODUCT", "ПРОПУСТИТЬ": "DROP", "БСТАНДОТКЛ": "DSTDEV",
    "БСТАНДОТКЛП": "DSTDEVP", "БСУММ": "DSUM", "ДЛИТ": "DURATION", "БДИСП": "DVAR",
    "БДИСПП": "DVARP", "ДАТАМЕС": "EDATE", "ЭФФЕКТ": "EFFECT", "КОНМЕСЯЦА": "EOMONTH",
    "ФОШ": "ERF", "ФОШ.ТОЧН": "ERF_PRECISE", "ДВФОШ": "ERFC", "ДВФОШ.ТОЧН": "ERFC_PRECISE",
    "ТИП.ОШИБКИ": "ERROR_TYPE", "ЧЁТН": "EVEN", "СОВПАД": "EXACT", "EXP": "EXP",
    "РАСШИРИТЬ": "EXPAND", "ЭКСП.РАСП": "EXPON_DIST", "ЭКСПРАСП": "EXPONDIST",
    "F.РАСП": "F_DIST", "F.РАСП.ПХ": "F_DIST_RT", "F.ОБР": "F_INV", "F.ОБР.ПХ": "F_INV_RT",
    "F.ТЕСТ": "F_TEST", "ФАКТР": "FACT", "ДВФАКТР": "FACTDOUBLE", "ЛОЖЬ": "FALSE",
    "FРАСП": "FDIST", "ФИЛЬТР": "FILTER", "НАЙТИ": "FIND", "НАЙТИБ": "FINDB",
    "FОБР": "FINV", "ФИШЕР": "FISHER", "ФИШЕРОБР": "FISHERINV",
    "ФИКСИРОВАННЫЙ": "FIXED", "ОКРВНИЗ": "FLOOR", "ОКРВНИЗ.МАТ": "FLOOR_MATH",
    "ОКРВНИЗ.ТОЧН": "FLOOR_PRECISE", "ПРЕДСКАЗ": "FORECAST", "ПРЕДСКАЗ.ETS": "FORECAST_ETS",
    "ПРЕДСКАЗ.ETS.ДОВИНТЕРВАЛ": "FORECAST_ETS_CONFINT",
    "ПРЕДСКАЗ.ETS.СЕЗОННОСТЬ": "FORECAST_ETS_SEASONALITY",
    "ПРЕДСКАЗ.ETS.СТАТ": "FORECAST_ETS_STAT", "ПРЕДСКАЗ.ЛИНЕЙН": "FORECAST_LINEAR",
    "Ф.ТЕКСТ": "FORMULATEXT", "ЧАСТОТА": "FREQUENCY", "FТЕСТ": "FTEST", "БС": "FV",
    "БЗРАСПИС": "FVSCHEDULE", "ГАММА": "GAMMA", "ГАММА.РАСП": "GAMMA_DIST",
    "ГАММА.ОБР": "GAMMA_INV", "ГАММАРАСП": "GAMMADIST", "ГАММАОБР": "GAMMAINV",
    "ГАММАНЛОГ": "GAMMALN", "ГАММАНЛОГ.ТОЧН": "GAMMALN_PRECISE", "ГАУСС": "GAUSS",
    "НОД": "GCD", "СРГЕОМ": "GEOMEAN", "ПОРОГ": "GESTEP",
    "ПОЛУЧИТЬ.СВОДНУЮ.ТАБЛИЦУ": "GETPIVOTDATA", "РОСТ": "GROWTH", "СРГАРМ": "HARMEAN",
    "ШЕСТН.В.ДВ": "HEX2BIN", "ШЕСТН.В.ДЕС": "HEX2DEC", "ШЕСТН.В.ВОСЬМ": "HEX2OCT",
    "ГПР": "HLOOKUP", "ЧАС": "HOUR", "ГСТОЛБЕЦ": "HSTACK", "ГИПЕРССЫЛКА": "HYPERLINK",
    "ГИПЕРГЕОМ.РАСП": "HYPGEOM_DIST", "ГИПЕРГЕОМЕТ": "HYPGEOMDIST", "ЕСЛИ": "IF",
    "ЕСЛИОШИБКА": "IFERROR", "ЕСЛИНД": "IFNA", "ЕСЛИМН": "IFS",
    "МНИМ.ABS": "IMABS", "ИЗОБРАЖЕНИЕ": "IMAGE", "МНИМ.ЧАСТЬ": "IMAGINARY",
    "МНИМ.АРГУМЕНТ": "IMARGUMENT", "МНИМ.СОПРЯЖ": "IMCONJUGATE", "МНИМ.COS": "IMCOS",
    "МНИМ.COSH": "IMCOSH", "МНИМ.COT": "IMCOT", "МНИМ.COTH": "IMCOTH",
    "МНИМ.CSC": "IMCSC", "МНИМ.CSCH": "IMCSCH", "МНИМ.ДЕЛ": "IMDIV", "МНИМ.EXP": "IMEXP",
    "МНИМ.LN": "IMLN", "МНИМ.LOG": "IMLOG", "МНИМ.LOG10": "IMLOG10",
    "МНИМ.LOG2": "IMLOG2", "МНИМ.СТЕПЕНЬ": "IMPOWER", "МНИМ.ПРОИЗВЕД": "IMPRODUCT",
    "МНИМ.ВЕЩ": "IMREAL", "МНИМ.SEC": "IMSEC", "МНИМ.SECH": "IMSECH",
    "МНИМ.SIN": "IMSIN", "МНИМ.SINH": "IMSINH", "МНИМ.КОРЕНЬ": "IMSQRT",
    "МНИМ.РАЗН": "IMSUB", "МНИМ.СУММ": "IMSUM", "МНИМ.TAN": "IMTAN",
    "МНИМ.TANH": "IMTANH", "ИНДЕКС": "INDEX", "ДВССЫЛ": "INDIRECT", "ИНФОРМ": "INFO",
    "ЦЕЛОЕ": "INT", "ОТРЕЗОК": "INTERCEPT", "ИНОРМА": "INTRATE", "ПРПЛТ": "IPMT",
    "ВСД": "IRR", "МЕЖДУ": "ISBETWEEN", "ЕПУСТО": "ISBLANK", "ЕДАТА": "ISDATE",
    "ЕОШ": "ISERR", "ЕОШИБКА": "ISERROR", "ЕЧЁТН": "ISEVEN", "ЕФОРМУЛА": "ISFORMULA",
    "ЕЛОГИЧ": "ISLOGICAL", "ЕНД": "ISNA", "ЕНЕТЕКСТ": "ISNONTEXT", "ЕЧИСЛО": "ISNUMBER",
    "ISO.ОКРВВЕРХ": "ISO_CEILING", "ЕНЕЧЁТ": "ISODD", "НЕ.ПРОПУЩЕНО": "ISOMITTED",
    "НОМНЕДЕЛИ.ISO": "ISOWEEKNUM", "ПРОЦПЛАТ": "ISPMT", "ЕССЫЛКА": "ISREF",
    "ЕТЕКСТ": "ISTEXT", "ЭКСЦЕСС": "KURT", "ЛЯМБДА": "LAMBDA", "НАИБОЛЬШИЙ": "LARGE",
    "НОК": "LCM", "ЛЕВСИМВ": "LEFT", "ЛЕВСИМВБ": "LEFTB", "ДЛСТР": "LEN", "ДЛСТРБ": "LENB",
    "ЛИНЕЙН": "LINEST", "LN": "LN", "LOG": "LOG", "LOG10": "LOG10",
    "ЛГРФПРИБЛ": "LOGEST", "ЛОГНОРМОБР": "LOGINV", "ЛОГНОРМ.РАСП": "LOGNORM_DIST",
    "ЛОГНОРМ.ОБР": "LOGNORM_INV", "ЛОГНОРМРАСП": "LOGNORMDIST", "ПРОСМОТР": "LOOKUP",
    "СТРОЧН": "LOWER", "СОЗДАТЬМАССИВ": "MAKEARRAY", "ОТОБРАЗИТЬ": "MAP",
    "ПОИСКПОЗ": "MATCH", "МАКС": "MAX", "МАКСА": "MAXA", "МАКСЕСЛИМН": "MAXIFS",
    "МОПРЕД": "MDETERM", "МДЛИТ": "MDURATION", "МЕДИАНА": "MEDIAN", "ПСТР": "MID",
    "ПСТРБ": "MIDB", "МИН": "MIN", "МИНА": "MINA", "МИНЕСЛИМН": "MINIFS",
    "МИНУТЫ": "MINUTE", "МОБР": "MINVERSE", "МВСД": "MIRR", "МУМНОЖ": "MMULT",
    "ОСТАТ": "MOD", "МОДА": "MODE", "МОДА.НСК": "MODE_MULT", "МОДА.ОДН": "MODE_SNGL",
    "МЕСЯЦ": "MONTH", "ОКРУГЛТ": "MROUND", "МУЛЬТИНОМ": "MULTINOMIAL",
    "МЕДИНИЦА": "MUNIT", "Ч": "N", "НД": "NA", "ОТРБИНОМ.РАСП": "NEGBINOM_DIST",
    "ОТРБИНОМРАСП": "NEGBINOMDIST", "ЧИСТРАБДНИ": "NETWORKDAYS",
    "ЧИСТРАБДНИ.МЕЖД": "NETWORKDAYS_INTL", "НОМИНАЛ": "NOMINAL",
    "НОРМ.РАСП": "NORM_DIST", "НОРМ.ОБР": "NORM_INV", "НОРМ.СТ.РАСП": "NORM_S_DIST",
    "НОРМ.СТ.ОБР": "NORM_S_INV", "НОРМРАСП": "NORMDIST", "НОРМОБР": "NORMINV",
    "НОРМСТРАСП": "NORMSDIST", "НОРМСТОБР": "NORMSINV", "НЕ": "NOT", "ТДАТА": "NOW",
    "КПЕР": "NPER", "ЧПС": "NPV", "ЧЗНАЧ": "NUMBERVALUE",
    "ВОСЬМ.В.ДВ": "OCT2BIN", "ВОСЬМ.В.ДЕС": "OCT2DEC", "ВОСЬМ.В.ШЕСТН": "OCT2HEX",
    "НЕЧЁТ": "ODD", "ЦЕНАПЕРВНЕРЕГ": "ODDFPRICE", "ДОХОДПЕРВНЕРЕГ": "ODDFYIELD",
    "ЦЕНАПОСЛНЕРЕГ": "ODDLPRICE", "ДОХОДПОСЛНЕРЕГ": "ODDLYIELD", "СМЕЩ": "OFFSET",
    "ИЛИ": "OR", "ПДЛИТ": "PDURATION", "ПИРСОН": "PEARSON", "ПЕРСЕНТИЛЬ": "PERCENTILE",
    "ПЕРСЕНТИЛЬ.ИСКЛ": "PERCENTILE_EXC", "ПЕРСЕНТИЛЬ.ВКЛ": "PERCENTILE_INC",
    "ПРОЦЕНТРАНГ": "PERCENTRANK", "ПРОЦЕНТРАНГ.ИСКЛ": "PERCENTRANK_EXC",
    "ПРОЦЕНТРАНГ.ВКЛ": "PERCENTRANK_INC", "ПЕРЕСТ": "PERMUT", "ПЕРЕСТА": "PERMUTATIONA",
    "ФИ": "PHI", "ПИ": "PI", "ПЛТ": "PMT", "ПУАССОН": "POISSON",
    "ПУАССОН.РАСП": "POISSON_DIST", "СТЕПЕНЬ": "POWER", "ОСПЛТ": "PPMT", "ЦЕНА": "PRICE",
    "ЦЕНАСКИДКА": "PRICEDISC", "ЦЕНАПОГАШ": "PRICEMAT", "ВЕРОЯТНОСТЬ": "PROB",
    "ПРОИЗВЕД": "PRODUCT", "ПРОПНАЧ": "PROPER", "ПС": "PV", "КВАРТИЛЬ": "QUARTILE",
    "КВАРТИЛЬ.ИСКЛ": "QUARTILE_EXC", "КВАРТИЛЬ.ВКЛ": "QUARTILE_INC",
    "ЧАСТНОЕ": "QUOTIENT", "РАДИАНЫ": "RADIANS", "СЛЧИС": "RAND",
    "СЛУЧМАССИВ": "RANDARRAY", "СЛУЧМЕЖДУ": "RANDBETWEEN", "РАНГ": "RANK",
    "РАНГ.СР": "RANK_AVG", "РАНГ.РВ": "RANK_EQ", "СТАВКА": "RATE", "ПОЛУЧЕНО": "RECEIVED",
    "СВЕРНУТЬ": "REDUCE", "РЕГУЛЯР.ИЗВЛЕЧЬ": "REGEXEXTRACT",
    "РЕГУЛЯР.СОВПАД": "REGEXMATCH", "РЕГУЛЯР.ЗАМЕНИТЬ": "REGEXREPLACE",
    "ЗАМЕНИТЬ": "REPLACE", "ЗАМЕНИТЬБ": "REPLACEB", "ПОВТОР": "REPT",
    "ПРАВСИМВ": "RIGHT", "ПРАВСИМВБ": "RIGHTB", "РИМСКОЕ": "ROMAN", "ОКРУГЛ": "ROUND",
    "ОКРУГЛ.БАНК": "ROUNDBANK", "ОКРУГЛВНИЗ": "ROUNDDOWN", "ОКРУГЛВВЕРХ": "ROUNDUP",
    "СТРОКА": "ROW", "ЧСТРОК": "ROWS", "ЭКВИВАЛСТАВКА": "RRI", "КВПИРСОН": "RSQ",
    "СКАНИРОВАНИЕ": "SCAN", "ПОИСК": "SEARCH", "ПОИСКБ": "SEARCHB", "SEC": "SEC",
    "SECH": "SECH", "СЕКУНДЫ": "SECOND", "ПОСЛЕДОВАТЕЛЬНОСТЬ": "SEQUENCE",
    "РЯД.СУММ": "SERIESSUM", "ЛИСТ": "SHEET", "ЛИСТЫ": "SHEETS", "ЗНАК": "SIGN",
    "SIN": "SIN", "SINH": "SINH", "СКОС": "SKEW", "СКОС.П": "SKEW_P", "АПЛ": "SLN",
    "НАКЛОН": "SLOPE", "НАИМЕНЬШИЙ": "SMALL", "СОРТИРОВКА": "SORT",
    "СОРТИРОВКА.ПО": "SORTBY", "КОРЕНЬ": "SQRT", "КОРЕНЬПИ": "SQRTPI",
    "НОРМАЛИЗАЦИЯ": "STANDARDIZE", "СТАНДОТКЛОН": "STDEV", "СТАНДОТКЛОН.П": "STDEV_P",
    "СТАНДОТКЛОН.В": "STDEV_S", "СТАНДОТКЛОНА": "STDEVA", "СТАНДОТКЛОНП": "STDEVP",
    "СТАНДОТКЛОНПА": "STDEVPA", "СТОШYX": "STEYX", "ПОДСТАВИТЬ": "SUBSTITUTE",
    "ПРОМЕЖУТОЧНЫЕ.ИТОГИ": "SUBTOTAL", "СУММ": "SUM", "СУММЕСЛИ": "SUMIF",
    "СУММЕСЛИМН": "SUMIFS", "СУММПРОИЗВ": "SUMPRODUCT", "СУММКВ": "SUMSQ",
    "СУММРАЗНКВ": "SUMX2MY2", "СУММСУММКВ": "SUMX2PY2", "СУММКВРАЗН": "SUMXMY2",
    "ПЕРЕКЛЮЧ": "SWITCH", "АСЧ": "SYD", "СТЬЮДЕНТ.РАСП": "T_DIST",
    "СТЬЮДЕНТ.РАСП.2Х": "T_DIST_2T", "СТЬЮДЕНТ.РАСП.ПХ": "T_DIST_RT",
    "СТЬЮДЕНТ.ОБР": "T_INV", "СТЬЮДЕНТ.ОБР.2Х": "T_INV_2T", "СТЬЮДЕНТ.ТЕСТ": "T_TEST",
    "ВЗЯТЬ": "TAKE", "TAN": "TAN", "TANH": "TANH", "РАВНОКЧЕК": "TBILLEQ",
    "ЦЕНАЧЕК": "TBILLPRICE", "ДОХОДЧЕК": "TBILLYIELD", "СТЬЮДРАСП": "TDIST",
    "ТЕКСТ": "TEXT", "ТЕКСТ.ПОСЛЕ": "TEXTAFTER", "ТЕКСТ.ДО": "TEXTBEFORE",
    "ОБЪЕДИНИТЬ": "TEXTJOIN", "ТЕКСТ.РАЗДЕЛИТЬ": "TEXTSPLIT", "ВРЕМЯ": "TIME",
    "ВРЕМЗНАЧ": "TIMEVALUE", "СТЬЮДРАСПОБР": "TINV", "ВСТОЛБЕЦ": "TOCOL",
    "СЕГОДНЯ": "TODAY", "ВСТРОКУ": "TOROW", "ТРАНСП": "TRANSPOSE",
    "ТЕНДЕНЦИЯ": "TREND", "СЖПРОБЕЛЫ": "TRIM", "УРЕЗСРЕДНЕЕ": "TRIMMEAN",
    "ИСТИНА": "TRUE", "ОТБР": "TRUNC", "СТЬЮДЕНТЕСТ": "TTEST", "ТИП": "TYPE",
    "ЮНИСИМВ": "UNICHAR", "УНИК": "UNIQUE", "ПРОПИСН": "UPPER", "ЗНАЧЕН": "VALUE",
    "ЗНАЧЕН.В.ТЕКСТ": "VALUETOTEXT", "ДИСПР": "VAR", "ДИСПР.П": "VAR_P",
    "ДИСПР.В": "VAR_S", "ДИСПРА": "VARA", "ДИСПРП": "VARP", "ДИСПРПА": "VARPA",
    "ПУО": "VDB", "ВПР": "VLOOKUP", "ДЕНЬНЕД": "WEEKDAY", "НОМНЕДЕЛИ": "WEEKNUM",
    "ВЕЙБУЛЛ": "WEIBULL", "ВЕЙБУЛЛ.РАСП": "WEIBULL_DIST", "РАБДЕНЬ": "WORKDAY",
    "РАБДЕНЬ.МЕЖД": "WORKDAY_INTL", "ЗАВЕРНУТЬ.ВСТОЛБЦЫ": "WRAPCOLS",
    "ЗАВЕРНУТЬ.ВСТРОКИ": "WRAPROWS", "ЧИСТВНДОХ": "XIRR", "ПРОСМОТРX": "XLOOKUP",
    "ПОИСКПОЗX": "XMATCH", "ЧИСТНЗ": "XNPV", "ИСКЛИЛИ": "XOR", "ГОД": "YEAR",
    "ДОЛЯГОДА": "YEARFRAC", "ДОХОД": "YIELD", "ДОХОДСКИДКА": "YIELDDISC",
    "ДОХОДПОГАШ": "YIELDMAT", "Z.ТЕСТ": "Z_TEST", "ZТЕСТ": "ZTEST",
    "НАКОПДОХОД": "ACCRINT", "НАКОПДОХОД.ПОГАШ": "ACCRINTM",
    "ПРОМЕЖУТОЧНЫЕ": "AGGREGATE", "ARRAY_CONSTRAIN": "ARRAY_CONSTRAIN",
    "ASC": "ASC", "CALL": "CALL", "CUBEKPIMEMBER": "CUBEKPIMEMBER",
    "CUBEMEMBER": "CUBEMEMBER", "CUBEMEMBERPROPERTY": "CUBEMEMBERPROPERTY",
    "CUBERANKEDMEMBER": "CUBERANKEDMEMBER", "CUBESET": "CUBESET",
    "CUBESETCOUNT": "CUBESETCOUNT", "CUBEVALUE": "CUBEVALUE", "DBCS": "DBCS",
    "ENCODEURL": "ENCODEURL", "EPOCHTODATE": "EPOCHTODATE",
    "EUROCONVERT": "EUROCONVERT", "FILTERXML": "FILTERXML", "FLATTEN": "FLATTEN",
    "LET": "LET", "MARGINOFERROR": "MARGINOFERROR", "NUMBERSTRING": "NUMBERSTRING",
    "REGISTER_ID": "REGISTER_ID", "RTD": "RTD", "T": "T", "UNICODE": "UNICODE",
    "WEBSERVICE": "WEBSERVICE",
}

_REPLACE_PATTERN = re.compile(
    r"(?:^|(?<=[=,(+\-*/^<>&|\s]))(" + "|".join(
        re.escape(ru) for ru in sorted(RU_TO_ENG, key=len, reverse=True)
    ) + r")(?=\s*\()",
)


def convert_russian_formula(formula: str) -> str:
    """Convert Russian function names in formula to English."""
    if not formula or not formula.startswith("="):
        return formula

    def _replace(m: re.Match) -> str:
        return RU_TO_ENG.get(m.group(1), m.group(1))

    return _REPLACE_PATTERN.sub(_replace, formula)
